var rand=Math.random,cosinus=Math.cos,sinus=Math.sin,pi=Math.PI,melee=1,cast=1,fire=1,air=1,water=1,slash=1,items={},models={},animations={},projectiles={},particles={},skills={},areas={},creatures={},powers={},mvMatrix=mat4.create(),mvMatrixStack=[],pMatrix=mat4.create(),mouseX,mouseY;function mvPushMatrix(){var a=mat4.create();mat4.set(mvMatrix,a);mvMatrixStack.push(a)}function mvPopMatrix(){if(mvMatrixStack.length==0)throw"Invalid popMatrix!";mvMatrix=mvMatrixStack.pop()}
function setMatrixUniforms(a){gl.uniformMatrix4fv(a.pMatrixUniform,!1,pMatrix);gl.uniformMatrix4fv(a.mvMatrixUniform,!1,mvMatrix)}function degToRad(a){return a*Math.PI/180}function setAptitudeVars(a){melee=a.melee.level;cast=a.cast.level;fire=a.fire.level;air=a.air.level;water=a.water.level;slash=a.slash.level}function randomPosInRect(a,b){var c={};c.x=a*(1-2*rand());c.y=b*(1-2*rand());return c}
function randomPosInCircle(a){var b={};do b.x=a*(1-2*rand()),b.y=a*(1-2*rand());while(b.x*b.x+b.y*b.y>a*a);return b}var DEBUG=!0;function info(a){var b=document.createElement("div");b.innerHTML="[INFO] "+a;document.getElementById("console").appendChild(b)}function debug(a){if(DEBUG){var b=document.createElement("div");b.innerHTML="[DEBUG] "+a;document.getElementById("console").appendChild(b)}}
function warning(a){var b=document.createElement("div");b.innerHTML="[WARNING] "+a;document.getElementById("console").appendChild(b)}function error(a){var b=document.createElement("div");b.innerHTML="[ERROR] "+a;document.getElementById("console").appendChild(b)}function clearConsole(){for(console=document.getElementById("console");console.hasChildNodes();)console.removeChild(console.firstChild)}function closeTab(a){document.getElementById(a).style.visibility="hidden"}
function dist(a,b){return Math.sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y))}function contains(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return!0;return!1}function faceNorm(a,b,c,d){var e={},f={};e.x=a[3*b]-a[3*c];e.y=a[3*b+1]-a[3*c+1];e.z=a[3*b+2]-a[3*c+2];f.x=a[3*b]-a[3*d];f.y=a[3*b+1]-a[3*d+1];f.z=a[3*b+2]-a[3*d+2];a={};a.x=e.y*f.z-e.z*f.y;a.y=e.z*f.x-e.x*f.z;a.z=e.x*f.y-e.y*f.x;e=Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z);a.x/=e;a.y/=e;a.z/=e;return a}
function handleLoadedTexture(a){gl.bindTexture(gl.TEXTURE_2D,a);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,a.image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);a.image.width==a.image.height?(gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT),gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT)):(gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,
gl.CLAMP_TO_EDGE),gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE));gl.bindTexture(gl.TEXTURE_2D,null)}function initTexture(a){var b=gl.createTexture();b.image=new Image;b.image.src=a;b.image.onload=function(){handleLoadedTexture(b)};return b}function loadMd5Mesh(a){var b=new XMLHttpRequest;b.open("GET","data/md5/"+a+".mesh",!0);b.onreadystatechange=function(){if(b.readyState==4&&b.responseText.length>0)models[a].mesh=parseMesh(b.responseText)};b.send(null)}
function loadMd5Anim(a){var b=new XMLHttpRequest;b.open("GET","data/md5/"+a+".anim",!0);b.onreadystatechange=function(){if(b.readyState==4&&b.responseText.length>0)animations[a].anim=parseAnim(b.responseText,a)};b.send(null)}function loadObj(a,b){var c=new XMLHttpRequest;c.open("GET","data/obj/"+a+"/"+a+".obj",!0);c.onreadystatechange=function(){if(c.readyState==4&&c.responseText.length>0)models[a].mesh=parseObj(c.responseText,"data/obj/"+a+"/",b)};c.send(null)}
function createArea(a,b,c,d){a=areas[a];a.numCreated?a.numCreated+=1:a.numCreated=1;var e={};if(a.shape.type=="circle"){e.radius=eval(a.shape.radius);e.level=d;e.x=b;e.y=c;for(var f=Math.random()*360,d=0;d<a.staticElements.length;d++)for(var g=0;g<eval(a.staticElements[d].count);g++){a.disposition||(f=Math.random()*360);for(var h=(1-rand()*2)*e.radius,i=(1-rand()*2)*e.radius,j=new Object3D(e.x+h,e.y+i,f,a.staticElements[d].model),l=j.collision?world.getCollisions(b+h,c+i,j.collision.radius):world.getCollisions(b+
h,c+i,0);h*h+i*i>e.radius*e.radius||world.paths[Math.round((h+b)/10)*world.map.w+Math.round((i+c)/10)]>0||l.length>0;)h=(1-rand()*2)*e.radius,i=(1-rand()*2)*e.radius,l=j.collision?world.getCollisions(b+h,c+i,j.collision.radius):world.getCollisions(b+h,c+i,0);j.moveTo(b+h,c+i);world.addObj(j)}for(d=0;d<a.creatures.length;d++)for(g=0;g<eval(a.creatures[d].count);g++){b=models[creatures[a.creatures[d].creature].modelName];do h=(1-rand()*2)*e.radius,i=(1-rand()*2)*e.radius,l=world.getCollisions(h,i,b.collision.radius);
while(h*h+i*i>e.radius*e.radius||l.length>0);j=new Character(creatures[a.creatures[d].creature],e.x+h,e.y+i,e.level);if(!creatures[a.creatures[d].creature].activation)j.circleHealth=new Object3D(0,0,0,"circleHealth"),j.circleHealth.z=0.1,j.circleHealth.parent=j;if(j.faction=="evil")j.ai=new AI(j);world.addObj(j)}}return e}var xpInc=2;
function Character(a,b,c,d){this.constitution={};this.strength={};this.intelligence={};this.dexterity={};this.melee={};this.ranged={};this.cast={};this.run={};this.block={};this.enchant={};this.hex={};this.traps={};this.stealth={};this.slash={};this.pierce={};this.blunt={};this.shield={};this.fire={};this.water={};this.earth={};this.air={};this.light={};this.dark={};this.aoe={};this.dot={};for(skill in this)this[skill].level=1,this[skill].xp=0;for(var e=0;e<a.aptitudes.length;e++)this[a.aptitudes[e].aptitude].level=
eval(a.aptitudes[e].level);this.scale=eval(a.scale);this.modelName=a.modelName;this.x=b;this.y=c;this.z=world.getH(this.x,this.y);this.orient=Math.random()*360;this.maxHp=eval(a.hpspmp[0]);this.maxMp=eval(a.hpspmp[1]);this.maxSp=eval(a.hpspmp[2]);this.currentHp=this.maxHp;this.currentMp=this.maxMp;this.currentSp=this.maxSp;this.faction=a.faction;this.inventory={};this.equipment={};if(a.equipmentModif)for(e=0;e<a.equipmentModif.length;e++)this.equipment[a.equipmentModif[e].type]=a.equipmentModif[e];
if(models[this.modelName].collision.type=="circle")this.collision=new CircleCollision(this,models[this.modelName].collision.radius*this.scale);else if(models[this.modelName].collision.type=="rect")this.collision=new RectCollision(this,models[this.modelName].collision.collisionW*this.scale,models[this.modelName].collision.collisionH*this.scale);this.baseDamages=[];this.currentDamages=[];if(a.damages){for(e=0;e<a.damages.length;e++)b={},b.value=eval(a.damages[e].value),b.range=a.damages[e].range,b.type=
a.damages[e].damageType,b.id="base",this.baseDamages.push(b),this.currentDamages.push(b);this.currentRange=this.baseRange=a.range}for(e=0;e<a.gear.length;e++)a.gear[e].weapon?(b=new Item(items[a.gear[e].weapon],"normal",d),this.addEquipment(b),a.name=="Player"&&(this.inventory[b.id]=b,$("#leftgear div").eq(3).append(getIcon(b)))):a.gear[e].shield&&(b=new Item(items[a.gear[e].shield],"normal",d),this.addEquipment(b),a.name=="Player"&&(this.inventory[b.id]=b,$("#rightgear div").eq(3).append(getIcon(b))));
a.particle&&world.particles.push(new ParticleEmitter(this,a.particle));this.properties=a;this.level=d;this.levelXP=10;this.currentAction=new Action(this,skills.idle);this.currentAction.isInterruptible=!0;this.nextAction=this.currentAction;this.currentFrame=animations[this.modelName][this.currentAction.type].firstFrame;this.nextFrame=animations[this.modelName][this.currentAction.type].firstFrame+1;this.posFrame=0}
Character.prototype.recover=function(a,b,c){this.currentHp=Math.min(this.currentHp+a,this.maxHp);this.currentSp=Math.min(this.currentSp+b,this.maxSp);this.currentMp=Math.min(this.currentMp+c,this.maxMp)};
Character.prototype.update=function(a){if(this.currentHp<this.maxHp&&this.currentHp>0){var b=(this.constitution.level+4)*(a/25);this.currentHp+=b;this.currentHp=Math.min(this.currentHp,this.maxHp);this.xpAptitude("constitution",a/3)}if(this.currentMp<this.maxMp&&this.currentHp>0)b=(this.intelligence.level+4)*(a/25),this.currentMp+=b,this.currentMp=Math.min(this.currentMp,this.maxMp),this.xpAptitude("intelligence",a/3);if(this.currentSp<this.maxSp&&this.currentHp>0)b=(this.strength.level+4)*(a/25),
this.currentSp+=b,this.currentSp=Math.min(this.currentSp,this.maxSp),this.xpAptitude("strength",a/3);if(this.currentHp<=0){this.currentHp=0;this.setAction(skills.die);if(this!=world.player)this.collision=null;this.circleHealth=null}this.z+=(world.getH(this.x,this.y)-this.z)/4;this.ai&&this.ai.process();this.currentAction.type.substring(0,4)=="walk"&&this.move(a);for(b=0;b<this.currentAction.lifeEffects.length;b++)this.currentAction.lifeEffects[b].parts||this.currentAction.lifeEffects[b].process(a)};
Character.prototype.draw=function(){mvPushMatrix();mat4.translate(mvMatrix,[this.x,this.y,this.z]);models[this.modelName].orient?mat4.rotate(mvMatrix,degToRad(models[this.modelName].orient+this.orient),[0,0,1]):mat4.rotate(mvMatrix,degToRad(this.orient),[0,0,1]);this.scale&&mat4.scale(mvMatrix,[this.scale,this.scale,this.scale]);for(equip in this.equipment)this.equipment[equip].bone&&this.equipment[equip].item&&this.equipment[equip].item.draw();this.circleHealth&&this.circleHealth.draw();if(this.mesh)this.mesh.draw();
else if(models[this.modelName].mesh)this.mesh=models[this.modelName].mesh;mvPopMatrix()};
Character.prototype.xpAptitude=function(a,b){if(this==world.player){this[a].xp+=b;if(this[a].xp>=this.levelXP)this[a].xp-=this.levelXP,this[a].level+=1,this.levelXP+=xpInc,this.level+=0.1,document.getElementById(a+"LVL").innerHTML=this[a].level,document.getElementById("playerLevel").innerHTML=Math.floor(this.level),document.getElementById("playerLevelXP").innerHTML=this.levelXP,a=="constitution"?this.maxHp+=2:a=="strength"?this.maxSp+=2:a=="intelligence"&&(this.maxMp+=2);document.getElementById(a+
"XP").innerHTML=Math.floor(this[a].xp)}};Character.prototype.damage=function(a){for(var b=0,c=0;c<a.length;c++)b+=a[c].value;this.currentHp-=b;this.currentAction.isInterruptible=!0;if(this.currentHp<=0){world.events.push(["dead",this]);this.currentHp=0;this.setAction(skills.die);if(this!=world.player)this.collision=null;this.circleHealth=null}else this.setAction(skills.hit);world.particles.push(new ParticleEmitter(this,"blood"));createNumber(this,Math.floor(b))};
Character.prototype.addEquipment=function(a){this.equipment[a.type]?this.equipment[a.type].item&&this.removeEquipment(a.type):this.equipment[a.type]={};this.equipment[a.type].item=a;a.parentModif=this.equipment[a.type];if(a.type=="weapon"){for(var b=0;b<this.currentDamages.length;b++)this.currentDamages[b].id=="base"&&this.currentDamages.splice(b,1);b={};b.value=a.damages;b.range=a.damageRange;b.type=a.damageType;b.id=a.id;this.currentDamages.push(b);this.currentRange=a.range}for(var c in a.powers)a.powers[c].effect.type==
"damage"?(b={},b.value=a.powers[c].effect.value,b.range=0,b.id=a.id,b.type=a.powers[c].effect.damageType,this.currentDamages.push(b)):a.powers[c].effect.type=="bonus"&&(a.powers[c].effect.aptitude=="hp"?this.maxHp+=a.powers[c].effect.value:a.powers[c].effect.aptitude=="sp"?this.maxSp+=a.powers[c].effect.value:a.powers[c].effect.aptitude=="mp"&&(this.maxMp+=a.powers[c].effect.value))};
Character.prototype.removeEquipment=function(a){var b=this.equipment[a].item,c;for(c in b.powers)if(b.powers[c].effect.type=="damage")for(var d=0;d<this.currentDamages.length;d++){if(this.currentDamages[d].id==b.id){this.currentDamages.splice(d,1);break}}else if(b.powers[c].effect.type=="bonus")if(b.powers[c].effect.aptitude=="hp")this.maxHp-=b.powers[c].effect.value,this.currentHp=Math.min(this.currentHp,this.maxHp);else if(b.powers[c].effect.aptitude=="sp")this.maxSp-=b.powers[c].effect.value,this.currentSp=
Math.min(this.currentSp,this.maxSp);else if(b.powers[c].effect.aptitude=="mp")this.maxMp-=b.powers[c].effect.value,this.currentMp=Math.min(this.currentMp,this.maxMp);this.equipment[a].item=null;if(a=="weapon"){for(d=0;d<this.currentDamages.length;d++)this.currentDamages[d].id==b.id&&this.currentDamages.splice(d,1);for(d=0;d<this.baseDamages.length;d++)this.currentDamages.push(this.baseDamages[d]);this.currentRange=this.baseRange}};
Character.prototype.setAction=function(a){if(this.nextAction.type!=a.action&&this.nextAction.type!="die"&&this.nextAction.type!="opened"&&this.nextAction.type!="disapear"&&this.nextAction.type!="hit"){setAptitudeVars(this);if(eval(a.cost[1])<=this.currentSp&&eval(a.cost[2])<=this.currentMp)this.nextAction=new Action(this,a);if(this.nextAction.type=="idle"||this.nextAction.type=="walkF"||this.nextAction.type=="walkB")this.nextAction.isInterruptible=!0}};
Character.prototype.move=function(a){if(!this.moveAngle)this.moveAngle=0;for(var b=(models[this.modelName].orient+this.orient+this.moveAngle)*Math.PI/180,c=this.x+this.speed*Math.sin(b)*a,a=this.y-this.speed*Math.cos(b)*a,b=this.getCollisions(c,a),d=!0,e=!0,f=0;f<b.length&&d;f++)if(!b[f].status||b[f].status.currentHp>0)if(d=!1,b[f].collision.tangent){var g=b[f].collision.tangent(this.x,this.y),h=g.x*(c-this.x)+g.y*(a-this.y);if(h<0)g.x=-g.x,g.y=-g.y,h=-h;for(var c=this.x+g.x*h,a=this.y+g.y*h,i=this.getCollisions(c,
a),j=0;j<i.length&&e;j++)e=e&&i[j].status&&i[j].status.currentHp<=0;if(e){if(this.ai){var i=Math.floor(this.x/(world.tileSize*world.gridSize)),j=Math.floor(this.y/(world.tileSize*world.gridSize)),l=Math.floor(c/(world.tileSize*world.gridSize)),q=Math.floor(a/(world.tileSize*world.gridSize));if(i!=l||j!=q)world.removeObjectFromGrid(this),world.grid[l][q].push(this)}this.x+=g.x*h;this.y+=g.y*h}}if(d&&e&&c&&a){if(this.ai&&(i=Math.floor(this.x/(world.tileSize*world.gridSize)),j=Math.floor(this.y/(world.tileSize*
world.gridSize)),l=Math.floor(c/(world.tileSize*world.gridSize)),q=Math.floor(a/(world.tileSize*world.gridSize)),i!=l||j!=q))world.removeObjectFromGrid(this),world.grid[l][q].push(this);this.x=c;this.y=a}};
Character.prototype.animate=function(a){this.update(a);for(animations[this.modelName][this.currentAction.type]&&this.currentAction.type!="disapear"&&(this.posFrame+=animations[this.modelName][this.currentAction.type].speed*a);this.posFrame>=1;)if(this.posFrame-=1,this.currentFrame=this.nextFrame,this.currentFrame>=animations[this.modelName][this.currentAction.type].lastFrame){for(var b=0;b<this.currentAction.finishEffects.length;b++)this.currentAction.finishEffects[b].process(a);if(this.currentAction.aptitudes)for(b=
0;b<this.currentAction.aptitudes.length;b++)this.xpAptitude(this.currentAction.aptitudes[b],1);if(this.currentAction.type=="die"){if(this.nextAction=new Action(this,skills.disapear),this!=world.player&&rand()<0.5)b=loot(this.level,rand()),b.x=this.x,b.y=this.y,b.z=this.z,world.addObj(b)}else if(this.currentAction.type=="open"){this.nextAction=new Action(this,skills.opened);var b=loot(this.level+1,rand()/5),c=(models[this.modelName].orient+this.orient)*Math.PI/180;b.x=this.x+Math.sin(c);b.y=this.y-
Math.cos(c);b.z=this.z;world.addObj(b)}else if(this.currentAction.type=="hit")this.nextAction=new Action(this,skills.idle),this.nextAction.isInterruptible=!0;for(b=0;b<this.currentAction.lifeEffects.length;b++)this.currentAction.lifeEffects[b].finalize();this.currentAction=this.nextAction;for(b=0;b<this.currentAction.lifeEffects.length;b++)this.currentAction.lifeEffects[b].alive&&world.particles.push(this.currentAction.lifeEffects[b]);this.setAction(skills.idle);this.currentHp-=this.currentAction.hpCost;
this.currentSp-=this.currentAction.spCost;this.currentMp-=this.currentAction.mpCost;this.nextFrame=animations[this.modelName][this.currentAction.type].firstFrame}else if(this.currentAction.isInterruptible&&this.currentAction.type!=this.nextAction.type){for(b=0;b<this.currentAction.lifeEffects.length;b++)this.currentAction.lifeEffects[b].finalize();this.currentAction=this.nextAction;for(b=0;b<this.currentAction.lifeEffects.length;b++)this.currentAction.lifeEffects[b].alive&&world.particles.push(this.currentAction.lifeEffects[b]);
this.setAction(skills.idle);this.currentHp-=this.currentAction.hpCost;this.currentSp-=this.currentAction.spCost;this.currentMp-=this.currentAction.mpCost;this.nextFrame=animations[this.modelName][this.currentAction.type].firstFrame}else this.nextFrame+=1;this.currentAction.type=="walk"&&this.setAction(skills.idle);if(this.boneAnim){for(var a=[],c=[],d=this.boneAnim[this.currentFrame].bonePos,e=this.boneAnim[this.nextFrame].bonePos,f=this.boneAnim[this.currentFrame].boneOrient,g=this.boneAnim[this.nextFrame].boneOrient,
b=0;b<this.mesh.bones.length;b++){for(var h=0;h<3;h++)c.push(d[b*3+h]*(1-this.posFrame)+e[b*3+h]*this.posFrame);h=new Quat(f[b*4],f[b*4+1],f[b*4+2]);h.w=f[b*4+3];var i=new Quat(g[b*4],g[b*4+1],g[b*4+2]);i.w=g[b*4+3];h=h.slerp(i,this.posFrame);a.push(h.x);a.push(h.y);a.push(h.z);a.push(h.w);for(equip in this.equipment)if(this.equipment[equip].bone&&this.equipment[equip].item&&this.equipment[equip].bone==b)this.equipment[equip].item.axisAngle=h.axisAngle(),this.equipment[equip].item.x=c[3*this.equipment[equip].bone],
this.equipment[equip].item.y=c[3*this.equipment[equip].bone+1],this.equipment[equip].item.z=c[3*this.equipment[equip].bone+2]}gl.useProgram(this.mesh.shaderProgram);gl.uniform4fv(this.mesh.shaderProgram.jointOrient,a);gl.uniform3fv(this.mesh.shaderProgram.jointPos,c)}else if(this.mesh&&animations[this.modelName]&&animations[this.modelName].anim)this.boneAnim=animations[this.modelName].anim};
Character.prototype.bindPose=function(){for(var a=[],b=[],c=0;c<this.mesh.bones.length;c++)a.push(this.mesh.bones[c].orient.x),a.push(this.mesh.bones[c].orient.y),a.push(this.mesh.bones[c].orient.z),a.push(this.mesh.bones[c].orient.w),b.push(this.mesh.bones[c].x),b.push(this.mesh.bones[c].y),b.push(this.mesh.bones[c].z);if(this.weapon)c=new Quat(a[4*this.weaponBone],a[4*this.weaponBone+1],a[4*this.weaponBone+2]),c.w=a[4*this.weaponBone+3],this.weapon.axisAngle=c.axisAngle(),c.rot(this.weapon.offx,
this.weapon.offy,this.weapon.offz),this.weapon.x=b[3*this.weaponBone],this.weapon.y=b[3*this.weaponBone+1],this.weapon.z=b[3*this.weaponBone+2];gl.useProgram(this.mesh.shaderProgram);gl.uniform4fv(this.mesh.shaderProgram.jointOrient,a);gl.uniform3fv(this.mesh.shaderProgram.jointPos,b)};
Character.prototype.getCollisions=function(a,b){for(var c=world.getObjNear(a,b,1),d=[],e=0;e<c.length;e++)c[e]!=this&&c[e].collision&&this.collision&&c[e].collision.collide(a,b,this.collision.radius)&&d.push(c[e]);return d};function CircleCollision(a,b){this.radius=b;this.parent=a}CircleCollision.prototype.collide=function(a,b,c){return Math.sqrt((this.parent.x-a)*(this.parent.x-a)+(this.parent.y-b)*(this.parent.y-b))<Math.max(c,this.radius)};
CircleCollision.prototype.tangent=function(a,b){var c={};if(a==this.parent.x)c.x=1,c.y=0;else if(b==this.parent.y)c.x=0,c.y=1;else{var d=Math.sqrt(1+Math.pow((this.parent.x-a)/(b-this.parent.y),2));c.x=1/d;c.y=(this.parent.x-a)/((b-this.parent.y)*d)}return c};function RectCollision(a,b,c){this.w=b;this.h=c;this.parent=a;this.radius=Math.sqrt(b*b+c*c)}
RectCollision.prototype.collide=function(a,b){var c=-this.parent.orient*Math.PI/180,d=Math.sin(c)*(a-this.parent.x)+Math.cos(c)*(b-this.parent.y);return Math.abs(Math.cos(c)*(a-this.parent.x)-Math.sin(c)*(b-this.parent.y))<this.w&&Math.abs(d)<this.h};
RectCollision.prototype.tangent=function(a,b){var c=-this.parent.orient*Math.PI/180,d={};Math.abs(Math.cos(c)*(a-this.parent.x)-Math.sin(c)*(b-this.parent.y))>this.w?(d.x=-Math.sin(this.parent.orient*Math.PI/180),d.y=Math.cos(this.parent.orient*Math.PI/180)):(d.x=Math.cos(this.parent.orient*Math.PI/180),d.y=Math.sin(this.parent.orient*Math.PI/180));c=Math.sqrt(d.x*d.x+d.y*d.y);d.x/=c;d.y/=c;return d};
function MeleeHit(a,b,c){this.parent=a;this.finishEffects=c;this.skill=b;this.damages=[];for(c=0;c<a.currentDamages.length;c++){var d={};d.type=a.currentDamages[c].type;d.value=a.currentDamages[c].value*eval(b.damagesModifier);d.value+=d.value*(1-2*rand())*eval(a.currentDamages[c].range);this.damages.push(d)}setAptitudeVars(a);if(b.damages)for(c=0;c<b.damages.length;c++)d={},d.type=b.damages[c].type,d.value=eval(b.damages[c].value),d.value+=d.value*(1-2*rand())*eval(b.damages[c].range),this.damages.push(d)}
MeleeHit.prototype.process=function(){var a=(models[this.parent.modelName].orient?this.parent.orient+models[this.parent.modelName].orient:this.parent.orient)*Math.PI/180,b=this.parent.collision&&this.parent.collision.radius?this.parent.collision.radius*1.2:1;b+=this.parent.currentRange;for(var a=this.parent.getCollisions(this.parent.x+Math.sin(a)*b,this.parent.y-Math.cos(a)*b),b=eval(this.skill.precision),c=0;c<a.length;c++)if(this.skill.target=="ennemy"&&a[c].faction&&a[c].faction!=this.parent.faction&&
a[c].currentHp>0)if(Math.random()<b/(b+a[c].dexterity.level)){a[c].damage(this.damages);for(var d=0;d<this.finishEffects.length;d++)world.particles.push(new ParticleEmitter(a[c],this.finishEffects[d]))}else a[c].xpAptitude("dexterity",1),world.particles.push(new ParticleEmitter(a[c],"miss"))};
function LineHit(a,b,c){this.parent=a;this.projectile=b;this.skill=c;this.damages=[];setAptitudeVars(a);for(a=0;a<c.damages.length;a++)b={},b.type=c.damages[a].type,b.value=eval(c.damages[a].value),c.damages[a].range&&(b.value+=b.value*(1-2*rand())*eval(c.damages[a].range)),this.damages.push(b)}
LineHit.prototype.process=function(){for(var a=world.getObjNear(this.parent.x,this.parent.y,1),b=(models[this.parent.modelName]&&models[this.parent.modelName].orient?this.parent.orient+models[this.parent.modelName].orient:this.parent.orient)*Math.PI/180,c=Math.sin(b),b=-Math.cos(b),d=0;d<a.length;d++){var e=Math.abs(c*(this.parent.y-a[d].y)-b*(this.parent.x-a[d].x));if(a[d].collision&&a[d].collision.radius&&e<Math.max(this.projectile.radius,a[d].collision.radius)&&this.skill.target=="ennemy"&&a[d].faction&&
a[d].faction!=this.parent.faction&&a[d].currentHp>0&&dist(a[d],this.parent)<this.projectile.range)a[d].damage(this.damages),this.projectile.dead=!0}};function ProjectileHit(a,b,c){this.parent=a;this.projectile=b;this.skill=c;this.damages=[];setAptitudeVars(a);for(a=0;a<c.damages.length;a++)b={},b.type=c.damages[a].type,b.value=eval(c.damages[a].value),c.damages[a].range&&(b.value+=b.value*(1-2*rand())*eval(c.damages[a].range)),this.damages.push(b)}
ProjectileHit.prototype.process=function(){for(var a=world.getCollisions(this.projectile.x,this.projectile.y,this.projectile.radius),b=0;b<a.length;b++)if(this.skill.target=="ennemy"&&a[b].faction&&a[b].faction!=this.parent.faction&&a[b].currentHp>0)a[b].damage(this.damages),this.projectile.dead=!0;else if(a[b]!=this.parent)this.projectile.dead=!0};
function Nova(a,b,c){this.parent=a;this.projectile=b;this.skill=c;this.damages=[];setAptitudeVars(a);for(a=this.lifeTime=0;a<c.damages.length;a++)b={},b.type=c.damages[a].type,b.value=eval(c.damages[a].value),c.damages[a].range&&(b.value+=b.value*(1-2*rand())*eval(c.damages[a].range)),this.damages.push(b);this.objsHit=[]}
Nova.prototype.process=function(a){this.lifeTime+=a;for(var a=world.getCollisions(this.projectile.x,this.projectile.y,this.lifeTime*this.projectile.radius/this.projectile.duration),b=0;b<a.length;b++)this.skill.target=="ennemy"&&a[b].faction&&a[b].faction!=this.parent.faction&&a[b].currentHp>0&&!contains(this.objsHit,a[b])&&(this.objsHit.push(a[b]),a[b].damage(this.damages))};
function RandomHit(a,b,c,d){this.parent=a;this.projectile=b;this.finishEffects=d;this.skill=c;this.damages=[];setAptitudeVars(a);for(a=0;a<c.damages.length;a++)b={},b.type=c.damages[a].type,b.value=eval(c.damages[a].value),c.damages[a].range&&(b.value+=b.value*(1-2*rand())*eval(c.damages[a].range)),this.damages.push(b)}
RandomHit.prototype.process=function(){for(var a=world.getCollisions(this.projectile.x,this.projectile.y,this.projectile.radius),b=[],c=0;c<a.length;c++)this.skill.target=="ennemy"&&a[c].faction&&a[c].faction!=this.parent.faction&&a[c].currentHp>0&&b.push(a[c]);if(b.length>0){a=Math.floor(rand()*b.length);b[a].damage(this.damages);for(c=0;c<this.finishEffects.length;c++)world.particles.push(new ParticleEmitter(b[a],this.finishEffects[c].particle))}};
function createNumber(a,b){for(var c=b==0?1:Math.floor(Math.log(b)/Math.log(10))+1,d=b,e=0;e<c;e++){var f={},g=models[a.modelName].orient?a.orient+models[a.modelName].orient:a.orient;a==world.player&&(g+=180);g=g*Math.PI/180;f.x=a.x+Math.cos(g)*(c/2-e-0.5)*0.4;f.y=a.y+Math.sin(g)*(c/2-e-0.5)*0.4;f.z=a.z;part=new ParticleEmitter(f,"num"+d%10);d=Math.floor(d/10);world.particles.push(part)}}function Disapear(a){this.parent=a;this.duration=0}
Disapear.prototype.process=function(a){this.duration+=a;this.duration>4&&(this.parent.z-=this.duration/10-0.4);if(this.duration>10)if(this.parent==world.player){this.parent.currentHp=1;this.parent.currentAction=new Action(this.parent,skills.idle);this.parent.nextAction=this.parent.currentAction;var a=models[creatures.Player.modelName],b=world.areas[0];do var c=(1-rand()*2)*b.radius,d=(1-rand()*2)*b.radius,e=world.getCollisions(b.x+c,b.y+d,a.collision.radius);while(c*c+d*d>b.radius*b.radius||e.length>
0);this.parent.x=b.x+c;this.parent.y=b.y+d}else world.removeObjectFromGrid(this.parent)};function AI(a){this.parent=a}
AI.prototype.process=function(){var a=dist(world.player,this.parent);if(a<30){var b=-this.parent.orient*Math.PI/180,c=Math.cos(b)*(world.player.x-this.parent.x)-Math.sin(b)*(world.player.y-this.parent.y),b=Math.sin(b)*(world.player.x-this.parent.x)+Math.cos(b)*(world.player.y-this.parent.y);if(this.parent.currentHp>0)b<=0||Math.abs(Math.atan(c/b))>0.1?(c<0?this.parent.orient+=180*elapsed:this.parent.orient-=180*elapsed,this.parent.speed=0,this.parent.setAction(skills.idle)):a>Math.max(this.parent.collision.radius*
1.1,world.player.collision.radius*1.1)?(c<0?this.parent.orient+=90*elapsed:this.parent.orient-=90*elapsed,this.parent.speed=6,this.parent.setAction(skills.walkF)):(this.parent.speed=0,world.player.currentHp>0?this.parent.setAction(skills["Melee attack"]):this.parent.setAction(skills.idle))}};var numPower={normal:"0",magic:"1+Math.floor(rand()*2)",rare:"3+Math.floor(rand()*2)",epic:"5+Math.floor(rand()*2)"},priceModif={normal:1,magic:2,rare:4,epic:8};
function Item(a,b){var c=a.modelName?new Object3D(0,0,0,a.modelName):new Object3D(0,0,0,null);c.name=a.name;c.type=a.type;c.requirements=a.requirements;if(c.type=="weapon")c.damageType=a.damageType,c.damages=a.damages,c.damageRange=a.damageRange,c.range=a.range;a.goldCost?(c.goldCost=a.goldCost*priceModif[b],c.description=a.description,c.icon=a.icon):c.goldCost=0;if(a.stackable)c.stackable=a.stackable;c.id=c.name+(new Date).getTime();c.quality=c.type=="consumable"?"normal":b;c.level=a.level;c.powers=
{};for(var d=0;d<eval(numPower[c.quality]);d++){var e=powers.list[Math.floor(rand()*powers.list.length)];if(c.powers[e.name])c.powers[e.name].effect.value=Math.round(10*(eval(e.effect.value)+c.powers[e.name].effect.value))/10;else{var f={effect:{}},g;for(g in e.effect)f.effect[g]=g=="value"?Math.round(10*eval(e.effect[g]))/10:e.effect[g];c.powers[e.name]=f}}return c}
function getIcon(a){var b=$("<div></div>").attr({"class":"item",id:a.id,name:a.name,style:"width:32;height:32;background-image:url(data/icons/"+a.icon+")"}).draggable({revert:"invalid",appendTo:"body",helper:"clone",start:function(){src=$(this).parent()}});b.mouseover(function(){$("#canvas3D").append(itemDescription(world.player.inventory[$(this).attr("id")]))}).mouseout(function(){$(".description").remove()});a.stackable&&(b.append("1"),b.attr({count:1}));b.addClass(a.type);items[a.name].type&&items[a.name].type==
"consumable"&&b.click(function(){var a=items[$(this).attr("name")].effect;a.recover&&world.player.recover(a.recover[0],a.recover[1],a.recover[2]);$(this).attr("count",eval($(this).attr("count"))-1);$(this).empty();$(this).append($(this).attr("count"));$(this).attr("count")=="0"&&($(this).remove(),delete world.player.inventory[$(this).attr("id")])});return b}
function itemDescription(a){setAptitudeVars(world.player);var b='<div class="description" style=left:'+mouseX+";top:"+mouseY+';><font color="#';a.quality=="normal"?b+="FFFFFF":a.quality=="magic"?b+="AAAAFF":a.quality=="rare"?b+="AAFFAA":a.quality=="epic"&&(b+="FFDDAA");b+='">'+a.name+" ("+a.type+")</font><br>"+a.description+"<br>";a.type=="weapon"&&(b+="Damages ("+a.damageType+") : "+(a.damages-a.damages*a.damageRange)+"-"+(a.damages+a.damages*a.damageRange)+", range : "+a.range+"<br>");for(var c in a.powers)b+=
"+ "+a.powers[c].effect.value+" ",a.powers[c].effect.type=="damage"?b+=a.powers[c].effect.damageType+" damage<br>":a.powers[c].effect.type=="bonus"&&(b+=a.powers[c].effect.aptitude+"<br>");a.goldCost>0&&(b+='<font color="#EEEEAA">Price: '+a.goldCost+" gold.</font>");b+="</div>";return b}
function loot(a,b){var c=[];for(x in items)items[x].droppable&&(!items[x].level||items[x].level<=a)&&c.push(items[x].name);c=new Item(items[c[Math.floor(rand()*c.length)]],b<0.01?"epic":b<0.05?"rare":b<0.2?"magic":"normal",a);c.pickable=new ParticleEmiter(c,"itemdrop");world.particles.push(c.pickable);return c}
function parseMesh(a){for(var b=a.indexOf("numJoints"),c=parseInt(a.substring(b+10,a.indexOf("\n",b))),b=a.indexOf("numMeshes",b),d=parseInt(a.substring(b+10,a.indexOf("\n",b))),e=a.substring(a.indexOf("joints",b),a.indexOf("}",b)).split("\n"),f=[],g=0;g<c;g++){var h=e[g+1],i={};i.nam=h.substring(h.indexOf('"')+1,h.lastIndexOf('"'));i.parent=f[parseInt(h.substring(h.lastIndexOf('"')+1,h.indexOf("(")-1))];b=h.substring(h.indexOf("(")+2,h.indexOf(")")).split(" ");i.x=parseFloat(b[0]);i.y=parseFloat(b[1]);
i.z=parseFloat(b[2]);h=h.substring(h.lastIndexOf("(")+2,h.lastIndexOf(")")).split(" ");i.orient=new Quat(parseFloat(h[0]),parseFloat(h[1]),parseFloat(h[2]));f.push(i)}c=new Mesh("anim");c.bones=f;for(h=e=0;h<d;h++){var b=a.indexOf("shader",b)+8,g=a.substring(b,a.indexOf('"',b)),b=a.indexOf("numverts",b),j=parseInt(a.substring(b+9,a.indexOf("\n",b))),l=a.substring(a.indexOf("vert 0",b),a.indexOf("numtris",b)).split("\n"),b=a.indexOf("numtris",b),q=parseInt(a.substring(b+8,a.indexOf("\n",b))),t=a.substring(a.indexOf("tri 0",
b),a.indexOf("numweights",b)).split("\n"),b=a.indexOf("numweights",b);parseInt(a.substring(b+11,a.indexOf("\n",b)));var s=a.substring(a.indexOf("weight 0",b)).split("\n");c.materials.push({});c.materials[h].faces=[];c.materials[h].textures=[];g.length>3&&c.materials[h].textures.push(initTexture("data/text/"+g));c.weight1=[];c.weight2=[];c.weightBlend=[];for(var n=[],g=0;g<j;g++){var o=l[g].substring(l[g].indexOf("(")+2).split(" "),p=parseInt(o[3]);c.textures.push(parseFloat(o[0]));c.textures.push(parseFloat(o[1]));
for(var o=parseInt(o[4]),v=0,r=0,y=0,u=p;u<p+o;u++){var m=s[u].split(" "),i=f[parseInt(m[2])],w=parseFloat(m[3]),m=i.orient.rot(parseFloat(m[5]),parseFloat(m[6]),parseFloat(m[7]));v+=(i.x+m.x)*w;r+=(i.y+m.y)*w;y+=(i.z+m.z)*w}m=s[p].split(" ");c.weight1.push(parseFloat(m[5]));c.weight1.push(parseFloat(m[6]));c.weight1.push(parseFloat(m[7]));c.weight1.push(parseFloat(m[2]));c.weightBlend.push(parseFloat(m[3]));o>1?(m=s[p+1].split(" "),c.weight2.push(parseFloat(m[5])),c.weight2.push(parseFloat(m[6])),
c.weight2.push(parseFloat(m[7])),c.weight2.push(parseFloat(m[2])),c.weightBlend.push(1-c.weightBlend[c.weightBlend.length-1])):(c.weight2.push(0),c.weight2.push(0),c.weight2.push(0),c.weight2.push(0),c.weightBlend.push(0));c.vertices.push(v);c.vertices.push(r);c.vertices.push(y);n.push([])}for(g=0;g<q;g++)m=t[g].split(" "),i=parseInt(m[2])+e,u=parseInt(m[3])+e,s=parseInt(m[4])+e,c.materials[h].faces.push(i),c.materials[h].faces.push(u),c.materials[h].faces.push(s),l={},o={},l.x=c.vertices[i*3]-c.vertices[u*
3],l.y=c.vertices[i*3+1]-c.vertices[u*3+1],l.z=c.vertices[i*3+2]-c.vertices[u*3+2],o.x=c.vertices[i*3]-c.vertices[s*3],o.y=c.vertices[i*3+1]-c.vertices[s*3+1],o.z=c.vertices[i*3+2]-c.vertices[s*3+2],m={},m.x=l.y*o.z-l.z*o.y,m.y=l.z*o.x-l.x*o.z,m.z=l.x*o.y-l.y*o.x,l=Math.sqrt(m.x*m.x+m.y*m.y+m.z*m.z),m.x/=l,m.y/=l,m.z/=l,n[i-e].push(m),n[u-e].push(m),n[s-e].push(m);for(g=0;g<j;g++){for(u=i=t=q=0;u<n[g].length;u++)q+=n[g][u].x,t+=n[g][u].y,i+=n[g][u].z;l=Math.sqrt(q*q+t*t+i*i);q/=l;t/=l;i/=l;c.normals.push(q);
c.normals.push(t);c.normals.push(i)}e+=j}c.initShaders();c.initBuffers();c.materials[0].textures.length>0&&gl.uniform1i(c.shaderProgram.useTexturesUniform,!0);return c}
function parseAnim(a,b){var c=a.indexOf("numFrames"),d=parseInt(a.substring(c+10,a.indexOf("\n",c))),c=a.indexOf("numJoints",c),e=parseInt(a.substring(c+10,a.indexOf("\n",c))),c=a.indexOf("frameRate");parseInt(a.substring(c+10,a.indexOf("\n",c)));c=a.indexOf("numAnimatedComponents",c);parseInt(a.substring(c+22,a.indexOf("\n",c)));for(var f=a.substring(a.indexOf("hierarchy",c),a.indexOf("}",c)).split("\n"),g=[],h=0;h<e;h++){var i=f[h+1],j={};j.nam=i.substring(i.indexOf('"')+1,i.lastIndexOf('"'));var l=
i.split("\t"),l=l[2].split(" ");j.parentNum=parseInt(l[0]);j.parent=g[j.parentNum];j.flag=parseInt(l[1]);j.startIndex=parseInt(l[2]);g.push(j)}f=[];for(h=0;h<d;h++){for(var j={bonePos:[],boneOrient:[]},c=a.indexOf("frame "+h,c),i=a.substring(c,a.indexOf("}",c)).split("\n"),q=0;q<e;q++){var l=i[q+1].split(" "),t=parseFloat(l[0]),s=parseFloat(l[1]),n=parseFloat(l[2]),l=new Quat(parseFloat(l[3]),parseFloat(l[4]),parseFloat(l[5]));if(g[q].parentNum>=0){var o=new Quat(j.boneOrient[g[q].parentNum*4],j.boneOrient[g[q].parentNum*
4+1],j.boneOrient[g[q].parentNum*4+2]);o.w=j.boneOrient[g[q].parentNum*4+3];n=o.rot(t,s,n);t=n.x+j.bonePos[g[q].parentNum*3];s=n.y+j.bonePos[g[q].parentNum*3+1];n=n.z+j.bonePos[g[q].parentNum*3+2];l=o.mul(l);l.normalize()}j.bonePos.push(t);j.bonePos.push(s);j.bonePos.push(n);j.boneOrient.push(l.x);j.boneOrient.push(l.y);j.boneOrient.push(l.z);j.boneOrient.push(l.w)}f.push(j)}if(animations[b].walkF)for(h=animations[b].walkF.lastFrame;h>=animations[b].walkF.firstFrame;h--)f.push(f[h]);return f}
function createMap(a,b,c,d,e){var f=new Mesh("terrain");f.materials.push({});f.materials[0].faces=[];f.materials[0].textures=[];for(var g=[],h=0;h<a;h++)for(var i=0;i<b;i++)f.vertices.push(h*d),f.vertices.push(i*d),f.vertices.push(c[h*b+i]),f.textures.push(h*1),f.textures.push(i*1),f.textures.push(e[h*b+i]),g.push([]);for(h=0;h<a-1;h++)for(i=0;i<b-1;i++)f.materials[0].faces.push(i*b+h),f.materials[0].faces.push(i*b+h+1),f.materials[0].faces.push((i+1)*b+h),c=faceNorm(f.vertices,i*b+h,i*b+h+1,(i+1)*
b+h),g[i*b+h].push(c),g[i*b+h+1].push(c),g[(i+1)*b+h].push(c),f.materials[0].faces.push(i*b+h+1),f.materials[0].faces.push((i+1)*b+h),f.materials[0].faces.push((i+1)*b+h+1),c=faceNorm(f.vertices,i*b+h,i*b+h+1,(i+1)*b+h),g[i*b+h+1].push(c),g[(i+1)*b+h].push(c),g[(i+1)*b+h+1].push(c);for(h=0;h<a;h++)for(i=0;i<b;i++){c={};c.x=0;c.y=0;for(k=c.z=0;k<g[h*b+i].length;k++)c.x+=g[h*b+i][k].x,c.y+=g[h*b+i][k].y,c.z+=g[h*b+i][k].z;c.x/=g[h*b+i].length;c.y/=g[h*b+i].length;c.z/=g[h*b+i].length;d=Math.sqrt(c.x*
c.x+c.y*c.y+c.z*c.z);f.normals.push(c.x/d);f.normals.push(c.y/d);f.normals.push(c.z/d)}f.initShaders();f.initBuffers();gl.uniform1i(f.shaderProgram.useTexturesUniform,!0);return f}
function loadTextures(a,b,c){spli=b.split("\n");for(var b={},d,e=0;e<spli.length;e++){var f=spli[e].split(" ");f[0]=="newmtl"&&(d=f[1]);f[0]=="map_Kd"&&!b[d]&&(b[d]=initTexture(c+f[1]))}mats=[];for(e=0;e<a.materials.length;e++)b[a.materials[e].matName]&&(a.materials[e].textures.push(b[a.materials[e].matName]),mats.push(a.materials[e]));a.materials=mats}
function parseObj(a,b,c){var d=a.split("\n"),e=new Mesh("static"),a=[],f=[],g={},h=[],i=-1E5,j=-1E5,l=1E5,q=1E5,t=1E7,s=new XMLHttpRequest;s.onreadystatechange=function(){s.readyState==4&&s.responseText.length>0&&loadTextures(e,s.responseText,b)};for(var n=0;n<d.length;n++){var o=d[n].split(" ");if(o[0]=="v"){var p=parseFloat(o[1]);f.push(p);l=Math.min(l,p);i=Math.max(i,p);p=parseFloat(o[3]);f.push(p);q=Math.min(q,p);j=Math.max(j,p);p=parseFloat(o[2]);f.push(p);t=Math.min(p,t)}else if(o[0]=="vt")h.push(parseFloat(o[1])),
h.push(parseFloat(o[2]));else if(o[0]=="f")for(r=1;r<4;r++){if(!(o[r]in g)){var v=o[r].split("/");e.vertices.push(f[3*parseInt(v[0])-3]);e.vertices.push(f[3*parseInt(v[0])-2]);e.vertices.push(f[3*parseInt(v[0])-1]);a.push([]);for(p=0;p<2;p++)e.textures.push(h[2*parseInt(v[1])+p-2]);g[o[r]]=e.vertices.length/3-1}e.materials[e.materials.length-1].faces.push(g[o[r]])}else if(o[0]=="mtllib")s.open("GET",b+o[1],!0);else if(o[0]=="usemtl")e.materials.push({}),p=e.materials[e.materials.length-1],p.textures=
[],p.faces=[],p.matName=o[1]}if(c)for(n=0;n<e.vertices.length/3;n++)e.vertices[3*n]-=(l+i)/2,e.vertices[3*n+1]-=(q+j)/2,e.vertices[3*n+2]-=t;s.send(null);for(p=0;p<e.materials.length;p++)for(n=0;n<e.materials[p].faces.length/3;n++)c={},h={},r=e.materials[p].faces[n*3],d=e.materials[p].faces[n*3+1],f=e.materials[p].faces[n*3+2],c.x=e.vertices[r*3]-e.vertices[d*3],c.y=e.vertices[r*3+1]-e.vertices[d*3+1],c.z=e.vertices[r*3+2]-e.vertices[d*3+2],h.x=e.vertices[r*3]-e.vertices[f*3],h.y=e.vertices[r*3+1]-
e.vertices[f*3+1],h.z=e.vertices[r*3+2]-e.vertices[f*3+2],g={},g.x=c.y*h.z-c.z*h.y,g.y=c.z*h.x-c.x*h.z,g.z=c.x*h.y-c.y*h.x,c=Math.sqrt(g.x*g.x+g.y*g.y+g.z*g.z),g.x/=c,g.y/=c,g.z/=c,a[r].push(g),a[d].push(g),a[f].push(g);for(n=0;n<e.vertices.length/3;n++){for(var r=f=d=p=0;r<a[n].length;r++)p+=a[n][r].x,d+=a[n][r].y,f+=a[n][r].z;c=Math.sqrt(p*p+d*d+f*f);p/=c;d/=c;f/=c;e.normals.push(p);e.normals.push(d);e.normals.push(f)}e.initShaders();e.initBuffers();gl.uniform1i(e.shaderProgram.useTexturesUniform,
!0);return e}
function createSky(){for(var a=new Mesh("static"),b=0;b<4;b++)a.materials.push({}),a.materials[b].textures=[],a.materials[b].faces=[4*b+0,4*b+1,4*b+2,4*b+1,4*b+2,4*b+3];a.materials[0].textures.push(initTexture("data/text/clouds1_north.jpg"));a.materials[1].textures.push(initTexture("data/text/clouds1_south.jpg"));a.materials[2].textures.push(initTexture("data/text/clouds1_east.jpg"));a.materials[3].textures.push(initTexture("data/text/clouds1_west.jpg"));a.vertices=[50,50,50,-50,50,50,50,50,-50,-50,
50,-50,50,-50,50,-50,-50,50,50,-50,-50,-50,-50,-50,50,50,50,50,-50,50,50,50,-50,50,-50,-50,-50,50,50,-50,-50,50,-50,50,-50,-50,-50,-50];a.textures=[1,1,0,1,1,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1,0,0,1,0,1,1,0,1,1,0,0,0];a.normals=[0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,0,-1];a.materials[0].faces=[0,1,2,1,2,3];a.initShaders();a.initBuffers();gl.uniform1i(a.shaderProgram.useTexturesUniform,!0);return a}
function createHealthCircle(){var a=new Mesh("health");a.materials.push({});a.materials[0].textures=[];a.materials[0].textures.push(initTexture("data/text/circleHealth.png"));a.vertices=[-1,-1,0.1,-1,1,0.1,1,-1,0.1,1,1,0.1];a.textures=[0,0,0,1,1,0,1,1];a.normals=[0,0,-1,0,0,-1,0,0,-1,0,0,-1];a.materials[0].faces=[0,1,2,1,2,3];a.initShaders();a.initBuffers();gl.uniform1i(a.shaderProgram.useTexturesUniform,!0);return a}
function Mesh(a){this.vertices=[];this.materials=[];this.normals=[];this.textures=[];this.type=a}
function getShader(a,b){var c=document.getElementById(b);if(!c)return null;for(var d="",e=c.firstChild;e;)e.nodeType==3&&(d+=e.textContent),e=e.nextSibling;if(c.type=="x-shader/x-fragment")c=a.createShader(a.FRAGMENT_SHADER);else if(c.type=="x-shader/x-vertex")c=a.createShader(a.VERTEX_SHADER);else return null;a.shaderSource(c,d);a.compileShader(c);if(!a.getShaderParameter(c,a.COMPILE_STATUS))return error(a.getShaderInfoLog(c)),null;return c}
Mesh.prototype.initShaders=function(){var a=getShader(gl,"shader-"+this.type+"-fs"),b=getShader(gl,"shader-"+this.type+"-vs");this.shaderProgram=gl.createProgram();gl.attachShader(this.shaderProgram,b);gl.attachShader(this.shaderProgram,a);gl.linkProgram(this.shaderProgram);gl.getProgramParameter(this.shaderProgram,gl.LINK_STATUS)||error("Could not initialise shaders");gl.useProgram(this.shaderProgram);if(this.type!="particle")this.shaderProgram.ambiantLight=gl.getUniformLocation(this.shaderProgram,
"uAmbiantLight"),this.shaderProgram.directionnalLight=gl.getUniformLocation(this.shaderProgram,"uDirectionnalLight");this.shaderProgram.normalsAttribute=gl.getAttribLocation(this.shaderProgram,"aNormals");gl.enableVertexAttribArray(this.shaderProgram.normalsAttribute);this.shaderProgram.textureCoordAttribute=gl.getAttribLocation(this.shaderProgram,"aTextureCoord");this.shaderProgram.pMatrixUniform=gl.getUniformLocation(this.shaderProgram,"uPMatrix");this.shaderProgram.mvMatrixUniform=gl.getUniformLocation(this.shaderProgram,
"uMVMatrix");this.shaderProgram.samplerUniform=[];this.shaderProgram.samplerUniform.push(gl.getUniformLocation(this.shaderProgram,"uSampler"));if(this.type=="anim")this.shaderProgram.weight1=gl.getAttribLocation(this.shaderProgram,"aWeightPosition1"),gl.enableVertexAttribArray(this.shaderProgram.weight1),this.shaderProgram.weight2=gl.getAttribLocation(this.shaderProgram,"aWeightPosition2"),gl.enableVertexAttribArray(this.shaderProgram.weight2),this.shaderProgram.weightBlend=gl.getAttribLocation(this.shaderProgram,
"weightBlend"),gl.enableVertexAttribArray(this.shaderProgram.weightBlend),this.shaderProgram.jointOrient=gl.getUniformLocation(this.shaderProgram,"jointOrient"),this.shaderProgram.jointPos=gl.getUniformLocation(this.shaderProgram,"jointPos"),this.shaderProgram.useTexturesUniform=gl.getUniformLocation(this.shaderProgram,"uUseTextures"),gl.uniform1i(this.shaderProgram.useTexturesUniform,!1);else if(this.type=="static")this.shaderProgram.vertices=gl.getAttribLocation(this.shaderProgram,"aVertexPosition"),
gl.enableVertexAttribArray(this.shaderProgram.vertices),this.shaderProgram.useTexturesUniform=gl.getUniformLocation(this.shaderProgram,"uUseTextures"),gl.uniform1i(this.shaderProgram.useTexturesUniform,!1);else if(this.type=="terrain")this.shaderProgram.vertices=gl.getAttribLocation(this.shaderProgram,"aVertexPosition"),gl.enableVertexAttribArray(this.shaderProgram.vertices),this.shaderProgram.samplerUniform.push(gl.getUniformLocation(this.shaderProgram,"uSampler2")),this.shaderProgram.samplerUniform.push(gl.getUniformLocation(this.shaderProgram,
"uSampler3")),this.shaderProgram.samplerUniform.push(gl.getUniformLocation(this.shaderProgram,"uSampler4"));else if(this.type=="health")this.shaderProgram.vertices=gl.getAttribLocation(this.shaderProgram,"aVertexPosition"),gl.enableVertexAttribArray(this.shaderProgram.vertices),this.shaderProgram.lifePercent=gl.getUniformLocation(this.shaderProgram,"lifePercent"),gl.uniform1f(this.shaderProgram.lifePercent,1);else if(this.type=="particle")this.shaderProgram.vertices=gl.getAttribLocation(this.shaderProgram,
"aVertexPosition"),gl.enableVertexAttribArray(this.shaderProgram.vertices),this.shaderProgram.time=gl.getUniformLocation(this.shaderProgram,"time"),gl.uniform1f(this.shaderProgram.time,0)};
Mesh.prototype.initBuffers=function(){if(this.normals.length>0)this.normalsBuffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,this.normalsBuffer),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.normals),gl.STATIC_DRAW),this.normalsBuffer.itemSize=3;if(this.textures.length>0)this.vertexTextureCoordBuffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,this.vertexTextureCoordBuffer),gl.useProgram(this.shaderProgram),gl.enableVertexAttribArray(this.shaderProgram.textureCoordAttribute),gl.bufferData(gl.ARRAY_BUFFER,
new Float32Array(this.textures),gl.STATIC_DRAW),this.vertexTextureCoordBuffer.itemSize=this.type=="particle"||this.type=="terrain"?3:2;for(var a=0;a<this.materials.length;a++)if(this.materials[a].faces)this.materials[a].elementBuffer=gl.createBuffer(),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.materials[a].elementBuffer),gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(this.materials[a].faces),gl.STATIC_DRAW),this.materials[a].elementBuffer.itemSize=1,this.materials[a].elementBuffer.numItems=
this.materials[a].faces.length;this.type=="anim"?(this.weight1Buffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,this.weight1Buffer),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.weight1),gl.STATIC_DRAW),this.weight1Buffer.itemSize=4,this.weight2Buffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,this.weight2Buffer),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.weight2),gl.STATIC_DRAW),this.weight2Buffer.itemSize=4,this.weightBlendBuffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,
this.weightBlendBuffer),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.weightBlend),gl.STATIC_DRAW),this.weightBlendBuffer.itemSize=2):(this.verticesBuffer=gl.createBuffer(),gl.bindBuffer(gl.ARRAY_BUFFER,this.verticesBuffer),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.vertices),gl.STATIC_DRAW),this.verticesBuffer.itemSize=3,this.verticesBuffer.numItems=this.vertices.length/3)};
Mesh.prototype.draw=function(){gl.useProgram(this.shaderProgram);this.type!="particle"&&(gl.uniform3f(this.shaderProgram.ambiantLight,0.2,0.2,0.2),gl.uniform3f(this.shaderProgram.directionnalLight,0.8,0.8,0.8));setMatrixUniforms(this.shaderProgram);gl.bindBuffer(gl.ARRAY_BUFFER,this.normalsBuffer);gl.vertexAttribPointer(this.shaderProgram.normalsAttribute,this.normalsBuffer.itemSize,gl.FLOAT,!1,0,0);this.type=="anim"?(gl.bindBuffer(gl.ARRAY_BUFFER,this.weight1Buffer),gl.vertexAttribPointer(this.shaderProgram.weight1,
this.weight1Buffer.itemSize,gl.FLOAT,!1,0,0),gl.bindBuffer(gl.ARRAY_BUFFER,this.weight2Buffer),gl.vertexAttribPointer(this.shaderProgram.weight2,this.weight2Buffer.itemSize,gl.FLOAT,!1,0,0),gl.bindBuffer(gl.ARRAY_BUFFER,this.weightBlendBuffer),gl.vertexAttribPointer(this.shaderProgram.weightBlend,this.weightBlendBuffer.itemSize,gl.FLOAT,!1,0,0)):(gl.bindBuffer(gl.ARRAY_BUFFER,this.verticesBuffer),gl.vertexAttribPointer(this.shaderProgram.vertices,this.verticesBuffer.itemSize,gl.FLOAT,!1,0,0));this.textures.length>
0&&(gl.bindBuffer(gl.ARRAY_BUFFER,this.vertexTextureCoordBuffer),gl.enableVertexAttribArray(this.shaderProgram.textureCoordAttribute),gl.vertexAttribPointer(this.shaderProgram.textureCoordAttribute,this.vertexTextureCoordBuffer.itemSize,gl.FLOAT,!1,0,0));for(var a=0;a<this.materials.length;a++){for(var b=0;b<this.materials[a].textures.length;b++)gl.activeTexture(gl.TEXTURE0+b),gl.bindTexture(gl.TEXTURE_2D,this.materials[a].textures[b]),gl.uniform1i(this.shaderProgram.samplerUniform[b],b);this.type!=
"particle"?(gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.materials[a].elementBuffer),gl.drawElements(gl.TRIANGLES,this.materials[a].elementBuffer.numItems,gl.UNSIGNED_SHORT,0)):gl.drawArrays(gl.POINTS,0,this.verticesBuffer.numItems)}};
Mesh.prototype.deleteBuffers=function(){this.normals.length>0&&gl.deleteBuffer(this.normalsBuffer);this.textures.length>0&&gl.deleteBuffer(this.vertexTextureCoordBuffer);for(var a=0;a<this.materials.length;a++)this.materials[a].faces&&gl.deleteBuffer(this.materials[a].elementBuffer);this.type=="anim"?(gl.deleteBuffer(this.weight1Buffer),gl.deleteBuffer(this.weight2Buffer),gl.deleteBuffer(this.weightBlendBuffer)):gl.deleteBuffer(this.verticesBuffer)};
function Object3D(a,b,c,d){this.x=a;this.y=b;this.z=0;this.orient=c;if(this.modelName=d)if(this.z=world.getH(this.x,this.y),this.scale=models[d].scale,models[d].sizeRange&&(this.scale+=this.scale*(1-2*rand())*models[d].sizeRange),models[d].orient&&(this.orient+=models[d].orient),models[d].collision)if(models[d].collision.type=="circle")this.collision=new CircleCollision(this,models[d].collision.radius*this.scale);else if(models[d].collision.type=="rect")this.collision=new RectCollision(this,models[d].collision.collisionW*
this.scale,models[d].collision.collisionH*this.scale)}Object3D.prototype.moveTo=function(a,b){this.x=a;this.y=b;this.z=world.getH(this.x,this.y)};
Object3D.prototype.draw=function(){mvPushMatrix();mat4.translate(mvMatrix,[this.x,this.y,this.z]);mat4.rotate(mvMatrix,degToRad(this.orient),[0,0,1]);this.axisAngle&&mat4.rotate(mvMatrix,degToRad(this.axisAngle.angle),[this.axisAngle.x,this.axisAngle.y,this.axisAngle.z]);this.parentModif&&(this.parentModif.trans&&mat4.translate(mvMatrix,[this.parentModif.trans.x,this.parentModif.trans.y,this.parentModif.trans.z]),this.parentModif.axisAngle&&mat4.rotate(mvMatrix,degToRad(this.parentModif.axisAngle.angle),
[this.parentModif.axisAngle.x,this.parentModif.axisAngle.y,this.parentModif.axisAngle.z]));this.scale&&mat4.scale(mvMatrix,[this.scale,this.scale,this.scale]);if(this.mesh)this.mesh.type=="health"&&(gl.useProgram(this.mesh.shaderProgram),gl.uniform1f(this.mesh.shaderProgram.lifePercent,this.parent.currentHp/this.parent.maxHp)),this.mesh.draw();else if(models[this.modelName].mesh)this.mesh=models[this.modelName].mesh;mvPopMatrix()};
function NumberParticule(a){this.loop=!1;this.duration=1;this.mesh=new Mesh("particle");this.mesh.materials.push({});this.mesh.materials[0].textures=[];this.mesh.materials[0].textures.push(initTexture("data/text/particle/numbers/"+a+".png"));this.mesh.vertices.push(0);this.mesh.vertices.push(0);this.mesh.vertices.push(3);this.mesh.normals.push(0);this.mesh.normals.push(0);this.mesh.normals.push(1);this.mesh.textures.push(-0.5);this.mesh.textures.push(0.7);this.mesh.textures.push(3);this.mesh.initShaders();
this.mesh.initBuffers()}function recPart(a,b,c,d,e,f){var g=a+eval(f.speedX),h=b+eval(f.speedY),i=c+eval(f.speedZ);d.vertices.push(a);d.vertices.push(b);d.vertices.push(c);d.normals.push(a-g);d.normals.push(b-h);d.normals.push(c-i);d.textures.push(eval(f.timeOffset));d.textures.push(eval(f.amplitude));d.textures.push(eval(f.imgSize));e>0&&recPart(g,h,i,d,e-1,f)}
function Particles(a){this.loop=a.loop;this.duration=a.duration;this.mesh=new Mesh("particle");this.mesh.materials.push({});this.mesh.materials[0].textures=[];this.mesh.materials[0].textures.push(initTexture("data/text/particle/"+a.img));var b=a.numParts;if(a.type&&a.type=="tree")recPart(eval(a.startX),eval(a.startY),eval(a.startZ),this.mesh,b,a);else for(var c=0;c<b;c++){if(a.startXY){var d=eval(a.startXY);this.mesh.vertices.push(d.x);this.mesh.vertices.push(d.y)}else this.mesh.vertices.push(eval(a.startX)),
this.mesh.vertices.push(eval(a.startY));this.mesh.vertices.push(eval(a.startZ));this.mesh.normals.push(eval(a.speedX));this.mesh.normals.push(eval(a.speedY));this.mesh.normals.push(eval(a.speedZ));this.mesh.textures.push(eval(a.timeOffset));this.mesh.textures.push(eval(a.amplitude));this.mesh.textures.push(eval(a.imgSize))}this.mesh.initShaders();this.mesh.initBuffers()}function ParticleEmitter(a,b){this.parent=a;this.currentTime=0;this.alive=!0;this.parts=particles[b]}
ParticleEmitter.prototype.process=function(a){gl.useProgram(this.parts.mesh.shaderProgram);this.currentTime+=a;if(this.currentTime>this.parts.duration)if(this.parts.loop)for(;this.currentTime>this.parts.duration;)this.currentTime-=this.parts.duration;else this.currentTime=this.parts.duration,this.alive=!1;gl.uniform1f(this.parts.mesh.shaderProgram.time,this.currentTime/this.parts.duration)};ParticleEmitter.prototype.finalize=function(){this.alive=!1};
ParticleEmitter.prototype.draw=function(){mvPushMatrix();mat4.translate(mvMatrix,[this.parent.x,this.parent.y,this.parent.z]);this.parent.orient&&mat4.rotate(mvMatrix,degToRad(this.parent.orient),[0,0,1]);this.parts.mesh.draw();mvPopMatrix()};
function Projectile(a,b,c,d){this.orient=a.parent.orient;eval(c.numProjs);this.parent=a;this.lifeDraw=[];this.finishDraw=[];this.x=eval(b.startX)+a.x;this.y=eval(b.startY)+a.y;this.h=eval(b.startZ)+a.z;this.vx=eval(b.speedX);this.vy=eval(b.speedY);this.vz=eval(b.speedZ);this.radius=eval(b.radius);this.duration=b.duration;this.dead=!1;b.loop?(this.loop=eval(b.loop),this.lastHit=0):this.loop=!1;if(b.range)this.range=b.range;this.damageInterval=b.damageInterval?eval(b.damageInterval):-1;for(d=0;d<b.lifeDraw.length;d++)b.lifeDraw[d].particle&&
this.lifeDraw.push(new ParticleEmiter(this,b.lifeDraw[d].particle));for(d=0;d<b.finishDraw.length;d++)b.finishDraw[d].particle&&this.finishDraw.push(new ParticleEmiter(this,b.finishDraw[d].particle));if(b.collisionEffect=="hit")this.collisionEffect=new ProjectileHit(a.parent,this,c);else if(b.collisionEffect=="line")this.collisionEffect=new LineHit(a.parent,this,c);else if(b.collisionEffect=="random")this.collisionEffect=new RandomHit(a.parent,this,c,b.randomDraw);else if(b.collisionEffect=="nova")this.collisionEffect=
new Nova(a.parent,this,c)}Projectile.prototype.update=function(a){this.x+=this.vx*a;this.y+=this.vy*a;this.z=world.getH(this.x,this.y)+this.vz*a;this.loop&&(this.lastHit+=a);if(!this.loop||this.lastHit>this.damageInterval)this.collisionEffect.process(a),this.lastHit=0;return this.dead};function Projectiles(a,b,c){this.parent=a;this.currentTime=0;this.duration=b.duration;this.x=a.x;this.y=a.y;this.z=a.z;this.projs=[];for(a=0;a<eval(c.numProjs);a++)this.projs.push(new Projectile(this,b,c,a))}
Projectiles.prototype.process=function(){world.addObj(this);for(var a=0;a<this.projs.length;a++)for(var b=0;b<this.projs[a].lifeDraw.length;b++)world.particles.push(this.projs[a].lifeDraw[b])};Projectiles.prototype.draw=function(){};
Projectiles.prototype.animate=function(a){this.currentTime+=a;for(var b=[],c=0;c<this.projs.length;c++)if(this.projs[c].update(a)){for(var d=0;d<this.projs[c].lifeDraw.length;d++)this.projs[c].lifeDraw[d].alive=!1;for(d=0;d<this.projs[c].finishDraw.length;d++)world.particles.push(this.projs[c].finishDraw[d])}else b.push(this.projs[c]);this.projs=b;if(this.currentTime>this.duration){world.removeObjectFromGrid(this);for(c=0;c<this.projs.length;c++){this.projs[c].collisionEffect.process(a);for(d=0;d<
this.projs[c].lifeDraw.length;d++)this.projs[c].lifeDraw[d].alive=!1;for(d=0;d<this.projs[c].finishDraw.length;d++)world.particles.push(this.projs[c].finishDraw[d])}}};function Quat(a,b,c){this.x=a;this.y=b;this.z=c;a=1-a*a-b*b-c*c;this.w=a<0?0:-Math.sqrt(a)}Quat.prototype.conj=function(){var a=new Quat(-this.x,-this.y,-this.z);a.w=this.w;return a};
Quat.prototype.mul=function(a){var b=new Quat(this.x*a.w+this.w*a.x+this.y*a.z-this.z*a.y,this.y*a.w+this.w*a.y+this.z*a.x-this.x*a.z,this.z*a.w+this.w*a.z+this.x*a.y-this.y*a.x);b.w=this.w*a.w-this.x*a.x-this.y*a.y-this.z*a.z;return b};Quat.prototype.rot=function(a,b,c){a=new Quat(a,b,c);a.w=0;a=this.mul(a);return a=a.mul(this.conj())};Quat.prototype.toString=function(){return"w: "+this.w+" x: "+this.x+" y: "+this.y+" z: "+this.z};
Quat.prototype.norm=function(){return Math.sqrt(this.w*this.w+this.x*this.x+this.y*this.y+this.z*this.z)};Quat.prototype.normalize=function(){var a=this.norm();a>0?(this.w/=a,this.x/=a,this.y/=a,this.z/=a):debug("Problem with computing quat norm : "+this)};Quat.prototype.dot=function(a){return this.w*a.w+this.x*a.x+this.y*a.y+this.z*a.z};
Quat.prototype.slerp=function(a,b){var c=new Quat(0,0,0),d,e;d=this.dot(a);if(d<0)this.x=-this.x,this.y=-this.y,this.z=-this.z,this.w=-this.w,d=-d;e=Math.acos(d);Math.sin(e)>0.0010?(d=Math.sin((1-b)*e)/Math.sin(e),e=Math.sin(b*e)/Math.sin(e)):(d=1-b,e=b);c.x=d*this.x+e*a.x;c.y=d*this.y+e*a.y;c.z=d*this.z+e*a.z;c.w=d*this.w+e*a.w;c.normalize();return c};
Quat.prototype.nlerp=function(a,b){var c=new Quat(0,0,0),d=1-b;c.x=d*this.x+b*a.x;c.y=d*this.y+b*a.y;c.z=d*this.z+b*a.z;c.w=d*this.w+b*a.w;c.normalize();return c};Quat.prototype.axisAngle=function(){var a=Math.sqrt(1-this.w*this.w),b={};b.angle=Math.acos(this.w)*360/Math.PI;a<1.0E-4?(b.x=this.x,b.y=this.y,b.z=this.z):(b.x=this.x/a,b.y=this.y/a,b.z=this.z/a);return b};
var questGrammar={"(quest)":["(knowledge)","(comfort)","(reputation)","(serenity)","(protection)","(conquest)","(wealth)","(ability)","(equipment)"],"(knowledge)":["(get) (goto) give","(goto) listen (goto) report","(get) (goto) use (goto) give"],"(comfort)":["(get) (goto) give"],"(reputation)":["(get) (goto) give","(goto) (kill) (goto) report","(goto) (goto) report"],"(serenity)":["(get) (goto) use (goto) give","(goto) listen (goto) report","(goto) take (goto) give","(get) (goto) give"],"(protection)":["(get) (goto) use",
"(get) (goto) use"],"(conquest)":["(goto) (steal) (goto) give"],"(wealth)":["(goto) (get)","(goto) (steal)","repair"],"(ability)":["repair use","(get) use","use","use","(get) use","(get) experiment"],"(equipment)":["repair","(get) (goto) give","(steal)","(goto) exchange"],"(subquest)":["(goto)","(goto) (quest) (goto)"],"(goto)":["","explore","(learn) goto"],"(learn)":["","(goto) (subquest) listen","(goto) (get) read","(get) (subquest) give listen"],"(get)":["","(steal)","(goto) gather","(goto) (get) (goto) (subquest) exchange"],
"(steal)":["(goto) (kill) take"],"(kill)":["(goto) kill"]};function expandQuest(a){for(var b="",a=a.split(" "),c=0;c<a.length;c++){var d=questGrammar[a[c]],d=d?d[Math.floor(rand()*d.length)]:a[c];b+=d;c<a.length-1&&d.length>0&&(b+=" ")}return b}var world,gl,lastTime=0,elapsed,viewDist=-10,currentlyPressedKeys={},pause=!1,keyMap={pause:80,aptitude:76,quests:75,settings:79,inventory:73,pick:81,activate:65,forward:69,strafeLeft:90,strafeRight:82,backward:68,turnLeft:83,turnRight:70,skill:84};
function initGL(a){try{gl=a.getContext("experimental-webgl"),gl.viewportWidth=a.width,gl.viewportHeight=a.height}catch(b){}gl||error("Could not initialise WebGL, sorry :-(")}function drawScene(){gl.viewport(0,0,gl.viewportWidth,gl.viewportHeight);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);mat4.perspective(45,gl.viewportWidth/gl.viewportHeight,0.1,1E3,pMatrix);mat4.identity(mvMatrix);mat4.translate(mvMatrix,[0,0,viewDist]);world&&world.draw(elapsed)}
function animate(){var a=(new Date).getTime();if(lastTime!=0)elapsed=(a-lastTime)/1E3,document.getElementById("frameRate").innerHTML="FPS : "+Math.round(1/elapsed);lastTime=a}function handleKeyDown(a){currentlyPressedKeys[a.keyCode]=!0}function handleKeyUp(a){currentlyPressedKeys[a.keyCode]=!1}
function handleKeys(){world.player.speed=0;if(currentlyPressedKeys[keyMap.forward]&&currentlyPressedKeys[keyMap.strafeLeft])world.player.speed=6,world.player.setAction(skills.walkF),animations[world.player.modelName].walkF.speed=world.player.speed*2,world.player.moveAngle=45;else if(currentlyPressedKeys[keyMap.forward]&&currentlyPressedKeys[keyMap.strafeRight])world.player.speed=6,world.player.setAction(skills.walkF),animations[world.player.modelName].walkF.speed=world.player.speed*2,world.player.moveAngle=
315;else if(currentlyPressedKeys[keyMap.backward]&&currentlyPressedKeys[keyMap.strafeLeft])world.player.speed=4,world.player.setAction(skills.walkB),animations[world.player.modelName].walkB.speed=world.player.speed*2,world.player.moveAngle=135;else if(currentlyPressedKeys[keyMap.backward]&&currentlyPressedKeys[keyMap.strafeRight])world.player.speed=4,world.player.setAction(skills.walkB),animations[world.player.modelName].walkB.speed=world.player.speed*2,world.player.moveAngle=225;else if(currentlyPressedKeys[keyMap.forward])world.player.speed=
8,world.player.setAction(skills.walkF),animations[world.player.modelName].walkF.speed=world.player.speed*2,world.player.moveAngle=0;else if(currentlyPressedKeys[keyMap.backward])world.player.speed=4,world.player.setAction(skills.walkB),animations[world.player.modelName].walkB.speed=world.player.speed*2,world.player.moveAngle=180;else if(currentlyPressedKeys[keyMap.strafeLeft])world.player.speed=4,world.player.setAction(skills.walkF),animations[world.player.modelName].walkF.speed=world.player.speed*
2,world.player.moveAngle=90;else if(currentlyPressedKeys[keyMap.strafeRight])world.player.speed=4,world.player.setAction(skills.walkF),animations[world.player.modelName].walkF.speed=world.player.speed*2,world.player.moveAngle=270;currentlyPressedKeys[keyMap.turnLeft]?world.player.orient+=90*elapsed:currentlyPressedKeys[keyMap.turnRight]&&(world.player.orient-=90*elapsed);currentlyPressedKeys[keyMap.skill]&&world.player.setAction(skills["Melee attack"]);currentlyPressedKeys[keyMap.aptitude]&&showTab("aptitude");
currentlyPressedKeys[keyMap.quests]&&showTab("quests");currentlyPressedKeys[keyMap.settings]&&showTab("settings");currentlyPressedKeys[keyMap.inventory]&&showTab("inventory");if(currentlyPressedKeys[keyMap.pick]){for(var a=world.getObjNear(world.player.x,world.player.y,1),b=[],c=0;c<a.length;c++)a[c].pickable&&dist(a[c],world.player)<2&&b.push(a[c]);a=$("#inventoryTable td:empty:eq(0)");if(b.length>0&&a.length>0)b=b[Math.floor(rand()*b.length)],world.removeObjectFromGrid(b),world.events.push(["picked",
b]),b.pickable.alive=!1,b.stackable&&$('div[name="'+b.name+'"]').length>0?(b=$('div[name="'+b.name+'"]').first(),b.attr("count",eval(b.attr("count"))+1),b.empty(),b.append(b.attr("count"))):(world.player.inventory[b.id]=b,a.append(getIcon(b)))}if(currentlyPressedKeys[keyMap.activate]){a=world.getObjNear(world.player.x,world.player.y,1);for(c=0;c<a.length;c++)if(a[c].properties&&a[c].properties.activation&&dist(a[c],world.player)<2&&a[c].currentAction.type=="idle")if(a[c].properties.activation.type==
"loot")a[c].currentAction=new Action(a[c],skills.open);else if(a[c].properties.activation.type=="trade")document.getElementById("vendorTab").style.visibility="visible"}}function showTab(a){currentlyPressedKeys[keyMap[a]]=!1;document.getElementById(a+"Tab").style.visibility=="hidden"?document.getElementById(a+"Tab").style.visibility="visible":document.getElementById(a+"Tab").style.visibility="hidden"}
function tick(){currentlyPressedKeys[keyMap.pause]&&(showTab("pause"),pause=!pause,lastTime=(new Date).getTime());pause||(world&&world.player&&handleKeys(),animate(),drawScene(),world&&world.processEvents())}
function webGLStart(){var a=document.getElementById("3d viewer");initGL(a);gl.clearColor(0,0,0,1);gl.clearDepth(1);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);setInterval(tick,20);document.onkeydown=handleKeyDown;document.onkeyup=handleKeyUp;initFromJSON();world=new World;for(var a="(quest)",b=0;b<3;b++)a=expandQuest(a),debug(a)}
function allLoaded(){return models.loaded&&animations.loaded&&items.loaded&&projectiles.loaded&&skills.loaded&&particles.loaded&&areas.loaded&&creatures.loaded&&powers.loaded}
function initJqueryFunc(){$("#canvas3D").mousemove(function(a){mouseX=a.pageX-this.offsetLeft;mouseY=a.pageY-this.offsetTop});$("#shortcutTable td").droppable({accept:".skill,.item.consumable",drop:function(a,b){src.attr("class")=="ui-droppable"&&$(this).children(src.droppable("option","accept")).length>0?src.append($(this).children(src.droppable("option","accept"))):$(this).children(".skill").length>0&&$(this).children().remove();$(this).children(".item").length==0&&$(this).append(b.draggable)}});
$("#inventoryTable td").droppable({accept:".item",drop:function(a,b){$(this).children(src.droppable("option","accept")).length>0&&src.append($(this).children());$(this).children(".item").length==0&&$(this).append(b.draggable);var c=src.droppable("option","accept");c.length>6&&(src.children().length>0?world.player.addEquipment(world.player.inventory[src.children().first().attr("id")]):world.player.removeEquipment(c.substring(6,c.length)))}});$("#leftgear div").eq(0).droppable({accept:".item.helmet",
drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#leftgear div").eq(1).droppable({accept:".item.pauldrons",drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#leftgear div").eq(2).droppable({accept:".item.gloves",drop:function(a,b){src.append($(this).children());
$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#leftgear div").eq(3).droppable({accept:".item.weapon",drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#leftgear div").eq(4).droppable({accept:".item.pants",drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});
$("#leftgear div").eq(5).droppable({accept:".item.boots",drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#rightgear div").eq(1).droppable({accept:".item.armor",drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#rightgear div").eq(3).droppable({accept:".item.shield",
drop:function(a,b){src.append($(this).children());$(this).append(b.draggable);world.player.addEquipment(world.player.inventory[$(this).children().first().attr("id")])}});$("#trash").droppable({accept:".item",drop:function(){delete world.player.inventory[src.children().first().attr("id")];src.children().remove();var a=src.droppable("option","accept");a.length>6&&world.player.removeEquipment(a.substring(6,a.length))}});$("#vendorTab").droppable({accept:".item",drop:function(){world.player.gold+=world.player.inventory[src.children().first().attr("id")].goldCost;
$("#gold").html(world.player.gold+" gold");delete world.player.inventory[src.children().first().attr("id")];src.children().remove();var a=src.droppable("option","accept");a.length>6&&world.player.removeEquipment(a.substring(6,a.length))}})}
function initWorld(a){a.loaded=!0;if(allLoaded()){initJqueryFunc();var b=world.graph,a=createArea("start",b[0].x,b[0].y,b[0].areaLevel);world.areas.push(a);var c=[];for(x in areas)x!="start"&&x!="loaded"&&c.push(x);for(var d=1;d<b.length;d++){for(var e=0,f=0;f<20;f++){do var g=(1-rand()*2)*30,h=(1-rand()*2)*30;while(g*g+h*h>1E3);e=Math.max(e,1-Math.abs(world.getNorm(b[d].x+g,b[d].y+h).z))}world.getH(b[d].x,b[d].y);do{g=Math.floor(rand()*c.length);h=!0;for(f=0;f<areas[c[g]].constrains.length;f++)h=
h&&eval(areas[c[g]].constrains[f])}while(!h);createArea(c[g],b[d].x,b[d].y,b[d].areaLevel)}for(f=0;f<c.length;f++)debug(areas[c[f]].numCreated+" "+c[f]);b=models[creatures.Player.modelName];do g=(1-rand()*2)*a.radius,h=(1-rand()*2)*a.radius,c=world.getCollisions(a.x+g,a.y+h,b.collision.radius);while(g*g+h*h>a.radius*a.radius||c.length>0);world.player=new Character(creatures.Player,a.x+g,a.y+h,1);world.player.gold=0}}
function initFromJSON(){var a=new XMLHttpRequest;a.open("GET","json/models.json",!0);a.onreadystatechange=function(){if(a.readyState==4&&a.responseText.length>0){for(var b=eval("("+a.responseText+")"),c=0;c<b.length;c++)if(models[b[c].modelName]=b[c],models[b[c].modelName].type=="md5")loadMd5Mesh(b[c].modelName);else if(models[b[c].modelName].type=="obj")loadObj(b[c].modelName,b[c].recenter);else if(models[b[c].modelName].type=="health")models[b[c].modelName].mesh=createHealthCircle();initWorld(models)}};
var b=new XMLHttpRequest;b.open("GET","json/animations.json",!0);b.onreadystatechange=function(){if(b.readyState==4&&b.responseText.length>0){for(var a=eval("("+b.responseText+")"),c=0;c<a.length;c++)animations[a[c].modelName]=a[c],loadMd5Anim(a[c].modelName);initWorld(animations)}};var c=new XMLHttpRequest;c.open("GET","json/items.json",!0);c.onreadystatechange=function(){if(c.readyState==4&&c.responseText.length>0){for(var a=eval("("+c.responseText+")"),b=0;b<a.length;b++)items[a[b].name]=a[b];
initWorld(items)}};var d=new XMLHttpRequest;d.open("GET","json/powers.json",!0);d.onreadystatechange=function(){if(d.readyState==4&&d.responseText.length>0)powers.list=eval("("+d.responseText+")"),initWorld(powers)};var e=new XMLHttpRequest;e.open("GET","json/areas.json",!0);e.onreadystatechange=function(){if(e.readyState==4&&e.responseText.length>0){for(var a=eval("("+e.responseText+")"),b=0;b<a.length;b++)areas[a[b].name]=a[b];initWorld(areas)}};var f=new XMLHttpRequest;f.open("GET","json/projectiles.json",
!0);f.onreadystatechange=function(){if(f.readyState==4&&f.responseText.length>0){for(var a=eval("("+f.responseText+")"),b=0;b<a.length;b++)projectiles[a[b].name]=a[b];initWorld(projectiles)}};var g=new XMLHttpRequest;g.open("GET","json/skills.json",!0);g.onreadystatechange=function(){if(g.readyState==4&&g.responseText.length>0){for(var a=eval("("+g.responseText+")"),b=0;b<a.length;b++)skills[a[b].name]=a[b];initWorld(skills)}};var h=new XMLHttpRequest;h.open("GET","json/creatures.json",!0);h.onreadystatechange=
function(){if(h.readyState==4&&h.responseText.length>0){for(var a=eval("("+h.responseText+")"),b=0;b<a.length;b++)creatures[a[b].name]=a[b];initWorld(creatures)}};var i=new XMLHttpRequest;i.open("GET","json/particles.json",!0);i.onreadystatechange=function(){if(i.readyState==4&&i.responseText.length>0){for(var a=eval("("+i.responseText+")"),b=0;b<a.length;b++){var c=new Particles(a[b]);particles[a[b].name]=c}initWorld(particles)}};b.send(null);c.send(null);d.send(null);e.send(null);f.send(null);g.send(null);
h.send(null);i.send(null);a.send(null);for(var j=0;j<10;j++)particles["num"+j]=new NumberParticule(j)}function handle(a){pause||(a<0?viewDist>-20&&(viewDist-=1):viewDist<1&&(viewDist+=1))}function wheel(a){var b=0;if(!a)a=window.event;a.wheelDelta?(b=a.wheelDelta/120,window.opera&&(b=-b)):a.detail&&(b=-a.detail/3);b&&handle(b);a.preventDefault&&a.preventDefault();a.returnValue=!1}window.addEventListener&&window.addEventListener("DOMMouseScroll",wheel,!1);
window.onmousewheel=document.onmousewheel=wheel;skills.idle=JSON.parse('{"name":"idle","cost": ["0","0","0"],"damages": [],"action": "idle","lifeEffects": [],"finishEffects": []}');skills.walkF=JSON.parse('{"name":"walkF","cost": ["0","0","0"],"damages": [],"action": "walkF","lifeEffects": [],"finishEffects": []}');skills.walkB=JSON.parse('{"name":"walkB","cost": ["0","0","0"],"damages": [],"action": "walkB","lifeEffects": [],"finishEffects": []}');skills.hit=JSON.parse('{"name":"hit","cost": ["0","0","0"],"damages": [],"action": "hit","lifeEffects": [],"finishEffects": []}');
skills.die=JSON.parse('{"name":"die","cost": ["0","0","0"],"damages": [],"action": "die","lifeEffects": [],"finishEffects": []}');skills.disapear=JSON.parse('{"name":"disapear","cost": ["0","0","0"],"damages": [],"action": "disapear","lifeEffects": ["disapear"],"finishEffects": []}');skills.open=JSON.parse('{"name":"open","cost": ["0","0","0"],"damages": [],"action": "open","lifeEffects": [],"finishEffects": []}');skills.opened=JSON.parse('{"name":"opened","cost": ["0","0","0"],"damages": [],"action": "opened","lifeEffects": [],"finishEffects": []}');
function Action(a,b){a==world.player&&setAptitudeVars(a);this.hpCost=eval(b.cost[0]);this.spCost=eval(b.cost[1]);this.mpCost=eval(b.cost[2]);this.type=b.action;this.isInterruptible=!1;this.lifeEffects=[];this.finishEffects=[];this.aptitudes=b.aptitudes;for(var c=0;c<b.lifeEffects.length;c++)b.lifeEffects[c]=="disapear"?this.lifeEffects.push(new Disapear(a)):b.lifeEffects[c].particle&&this.lifeEffects.push(new ParticleEmitter(a,b.lifeEffects[c].particle));for(c=0;c<b.finishEffects.length;c++)b.finishEffects[c].MeleeHit?
this.finishEffects.push(new MeleeHit(a,b,b.finishEffects[c].MeleeHit)):b.finishEffects[c].projectiles&&this.finishEffects.push(new Projectiles(a,projectiles[b.finishEffects[c].projectiles],b))}
function skillDescription(a){setAptitudeVars(world.player);var b='<div class="description" style=left:'+(mouseX+2)+";top:"+(mouseY+2)+';><font color="#AAFFAA">'+skills[a].name+"</font><br>"+skills[a].description+"<br>Cost:";eval(skills[a].cost[0])>0&&(b+=' <font color="#FF7777">'+eval(skills[a].cost[0])+" HP</font>");eval(skills[a].cost[1])>0&&(b+=' <font color="#FFFF77">'+eval(skills[a].cost[1])+" SP</font>");eval(skills[a].cost[2])>0&&(b+=' <font color="#7777FF">'+eval(skills[a].cost[2])+" MP</font>");
for(var c=0,d=0,e=0;e<world.player.currentDamages.length;e++){var f=world.player.currentDamages[e].value*eval(skills[a].damagesModifier);c+=f-f*eval(world.player.currentDamages[e].range);d+=f+f*eval(world.player.currentDamages[e].range)}if(skills[a].damages)for(e=0;e<skills[a].damages.length;e++)f=eval(skills[a].damages[e].value),c+=f-f*eval(skills[a].damages[e].range),d+=f+f*eval(skills[a].damages[e].range);c>0&&(b+=" Damages: "+Math.round(c*100)/100+"-"+Math.round(d*100)/100);b+="</div>";return b}
function aptitudeButton(a){var b=document.getElementById("skillTable");if(b.hasChildNodes())for(;b.childNodes.length>=1;)b.removeChild(b.firstChild);for(var c in skills){var b=!1,d=0;if(skills[c].aptitudes)for(var e=0;e<skills[c].aptitudes.length;e++)b=b||skills[c].aptitudes[e]==a,d+=world.player[skills[c].aptitudes[e]].level;skills[c].icon&&b&&d>=skills[c].level&&(b=$("<div></div>").attr({"class":"skill",skill:c,id:skills[c].name,style:"width:32;height:32;background-image:url(data/icons/"+skills[c].icon+
")"}).draggable({revert:"invalid",appendTo:"body",helper:"clone",start:function(){src=$(this).parent()}}),b.mouseover(function(){$("#canvas3D").append(skillDescription($(this).attr("skill")))}).mouseout(function(){$(".description").remove()}),d=$("<tr></tr>").append($("<td></td>").append(b)),b.click(function(){world.player.setAction(skills[$(this).attr("skill")])}),d.append($("<td></td>").append(c)),$("#skillTable").append(d))}document.getElementById("skillTab").style.visibility="visible"}
World=function(){this.player=null;this.grid=[];this.areas=[];this.objectsWithAlpha=[];this.particles=[];this.gridSize=this.tileSize=10;this.events=[];this.graph=this.generateTerrain(7)};function diamond(a,b,c,d,e,f,g){e[(c+d)/2*f+(a+b)/2]=(e[c*f+a]+e[c*f+b]+e[d*f+a]+e[d*f+b])/4+(1-2*rand())*g}function square(a,b,c,d,e,f,g){var h=0;h+=a+c>=e?d[b*e+a-c]:d[b*e+a+c];h+=a-c<0?d[b*e+a+c]:d[b*e+a-c];h+=b+c>=f?d[(b-c)*e+a]:d[(b+c)*e+a];h+=b-c<0?d[(b+c)*e+a]:d[(b-c)*e+a];h/=4;d[b*e+a]=h+(1-2*rand())*g}
function paintPath(a,b,c,d){var e=Math.round(a.x/10),f=Math.round(b.x/10),a=Math.round(a.y/10),b=Math.round(b.y/10),g=f-e,h=1,i=b-a,j=1;g<0&&(h=-1,g=-g);i<0&&(j=-1,i=-i);g<<=1;i<<=1;d[e*c+a]=2;if(i<g)for(var l=i-(g>>1);e!=f;)l>=0&&(a+=j,l-=g,d[e*c+a]=2),l+=i,e+=h,d[e*c+a]=2;else for(l=g-(i>>1);a!=b;)l>=0&&(e+=h,l-=i,d[e*c+a]=2),l+=g,a+=j,d[e*c+a]=2}
World.prototype.generateTerrain=function(a){this.map=new Object3D(0,0,0,null);this.map.w=Math.pow(2,a)+1;this.map.h=Math.pow(2,a)+1;for(var b=0;b<this.map.w/this.gridSize;b++){this.grid.push([]);for(var c=0;c<this.map.h/this.gridSize;c++)this.grid[b].push([])}for(var d=[],b=0;b<this.map.w*this.map.h;b++)d.push(0);for(b=0;b<3;b++)for(c=0;c<2;c++)d[c*(this.map.h-1)/2*this.map.w+b*(this.map.w-1)/2]=rand()*140;for(var e=80,f=1;f<a;f++){for(b=0;b<Math.pow(2,f);b++)for(c=0;c<Math.pow(2,f);c++){var g=Math.pow(2,
a-f);diamond(b*g,(b+1)*g,c*g,(c+1)*g,d,this.map.w,e);square(b*g,c*g+g/2,g/2,d,this.map.w,this.map.h,e);square(b*g+g/2,c*g,g/2,d,this.map.w,this.map.h,e);square((b+1)*g,c*g+g/2,g/2,d,this.map.w,this.map.h,e);square(b*g+g/2,(c+1)*g,g/2,d,this.map.w,this.map.h,e)}e/=2}for(f=0;f<10;f++)for(b=1;b<this.map.w-1;b++)for(c=1;c<this.map.h-1;c++)d[c*this.map.w+b]=(d[(c-1)*this.map.w+b-1]+d[(c-1)*this.map.w+b]+d[(c-1)*this.map.w+b+1]+d[c*this.map.w+b-1]+d[c*this.map.w+b]+d[c*this.map.w+b+1]+d[(c+1)*this.map.w+
b-1]+d[(c+1)*this.map.w+b]+d[(c+1)*this.map.w+b+1])/9;a=[];for(b=0;b<30;b++){e={};do{e.x=150+Math.random()*(this.map.w*this.tileSize-300);e.y=150+Math.random()*(this.map.h*this.tileSize-300);f=this.map.w*this.map.h;for(c=0;c<a.length;c++)f=Math.min(f,dist(e,a[c]))}while(f<150);e.nei=[];for(c=0;c<a.length;c++)dist(e,a[c])<220&&(e.nei.push(a[c]),a[c].nei.push(e));a.push(e)}this.paths=[];for(b=0;b<this.map.w*this.map.h;b++)this.paths.push(0);for(b=0;b<a.length;b++)for(c=0;c<a[b].nei.length;c++)paintPath(a[b],
a[b].nei[c],this.map.w,this.paths);e=[];f=[a[0]];for(g=0;f.length>0;){for(var h=[],b=0;b<f.length;b++)if(!contains(e,f[b])){e.push(f[b]);if(!f[b].areaLevel)f[b].areaLevel=g;for(c=0;c<f[b].nei.length;c++)!contains(e,f[b].nei[c])&&!contains(h,f[b].nei[c])&&h.push(f[b].nei[c])}g+=1;f=h}for(b=1;b<a.length;b++)if(!a[b].areaLevel)a[b].areaLevel=Math.ceil(10*rand());debug(e.length+"nodes visited");this.map.mesh=createMap(this.map.w,this.map.h,d,this.tileSize,this.paths);b=initTexture("data/text/grassC.jpg");
c=initTexture("data/text/rockC.jpg");d=initTexture("data/text/snowC.jpg");e=initTexture("data/text/dirtC.jpg");this.map.mesh.materials[0].textures.push(b);this.map.mesh.materials[0].textures.push(c);this.map.mesh.materials[0].textures.push(d);this.map.mesh.materials[0].textures.push(e);this.map.sky=new Object3D(0,0,0,null);this.map.sky.mesh=createSky();return a};World.prototype.addObj=function(a){this.grid[Math.floor(a.x/(this.tileSize*this.gridSize))][Math.floor(a.y/(this.tileSize*this.gridSize))].push(a)};
World.prototype.getH=function(a,b){if(this.map&&a/this.tileSize<this.map.w&&b/this.tileSize<this.map.h){var c=Math.floor(a/this.tileSize),d=Math.floor(b/this.tileSize),e,f=this.map.h,g=this.map.mesh.vertices;e=1-a/this.tileSize+c>b/this.tileSize-d?faceNorm(g,c*f+d,(c+1)*f+d,c*f+d+1):faceNorm(g,(c+1)*f+d,c*f+d+1,(c+1)*f+d+1);return(-e.x*a-e.y*b-(-e.x*g[3*(c*f+d+1)]-e.y*g[3*(c*f+d+1)+1]-e.z*g[3*(c*f+d+1)+2]))/e.z}else return 0};
World.prototype.getNorm=function(a,b){if(this.map&&a/this.tileSize<this.map.w&&b/this.tileSize<this.map.h){var c=Math.floor(a/this.tileSize),d=Math.floor(b/this.tileSize),e=this.map.h,f=this.map.mesh.vertices;return 1-a/this.tileSize+c>b/this.tileSize-d?faceNorm(f,c*e+d,(c+1)*e+d,c*e+d+1):faceNorm(f,(c+1)*e+d,c*e+d+1,(c+1)*e+d+1)}else debug(a+","+b+" not in map")};
World.prototype.removeObjectFromGrid=function(a){for(var b=Math.floor(a.x/(this.tileSize*this.gridSize)),c=Math.floor(a.y/(this.tileSize*this.gridSize)),d=0;d<this.grid[b][c].length;d++)if(this.grid[b][c][d]==a){this.grid[b][c].splice(d,1);break}};
World.prototype.getObjNear=function(a,b,c){for(var d=[],a=Math.floor(a/(this.tileSize*this.gridSize)),b=Math.floor(b/(this.tileSize*this.gridSize)),e=Math.max(0,a-c);e<=Math.min(this.grid.length-1,a+c);e++)for(var f=Math.max(0,b-c);f<=Math.min(this.grid[e].length-1,b+c);f++)for(var g=0;g<this.grid[e][f].length;g++)d.push(this.grid[e][f][g]);world.player&&d.push(world.player);return d};
World.prototype.getCollisions=function(a,b,c){for(var d=this.getObjNear(a,b,1),e=[],f=0;f<d.length;f++)d[f].collision&&d[f].collision.collide(a,b,c)&&e.push(d[f]);return e};World.prototype.sortZ=function(){for(var a=[];this.objectsWithAlpha.length>0;){for(var b=-1,c=-1,d=0;d<this.objectsWithAlpha.length;d++){var e=dist(this.objectsWithAlpha[d],this.player);e>b&&(b=e,c=d)}a.push(this.objectsWithAlpha[c]);this.objectsWithAlpha.splice(c,1)}this.objectsWithAlpha=a};
World.prototype.processEvents=function(){for(var a=0;a<this.events.length;a++)debug(this.events[a][1].modelName+" "+this.events[a][0]);this.events=[]};
World.prototype.draw=function(a){this.player&&(mat4.rotate(mvMatrix,degToRad(-70),[1,0,0]),mat4.rotate(mvMatrix,degToRad(-this.player.orient),[0,0,1]),mat4.translate(mvMatrix,[-this.player.x,-this.player.y,-this.player.z-2]));if(this.map.sky&&this.player)this.map.sky.x=this.player.x,this.map.sky.y=this.player.y,this.map.sky.z=this.getH(this.map.sky.x,this.map.sky.y),this.map.sky.draw(),gl.clear(gl.DEPTH_BUFFER_BIT);this.map.mesh&&this.map.draw();a||(a=0);if(this.player){if(this.player.currentHp>=
0)document.getElementById("hp").innerHTML="HP : "+Math.ceil(10*this.player.currentHp)/10+"/"+this.player.maxHp,document.getElementById("sp").innerHTML="SP : "+Math.floor(10*this.player.currentSp)/10+"/"+this.player.maxSp,document.getElementById("mp").innerHTML="MP : "+Math.floor(10*this.player.currentMp)/10+"/"+this.player.maxMp,document.getElementById("imHp").width=150*this.player.currentHp/this.player.maxHp,document.getElementById("imSp").width=150*this.player.currentSp/this.player.maxSp,document.getElementById("imMp").width=
150*this.player.currentMp/this.player.maxMp;for(var b=document.getElementById("viewDist").value,c=this.getObjNear(this.player.x,this.player.y,Math.round(b/100)),d=0;d<c.length;d++){var e=dist(this.player,c[d]);if(e<b&&c[d].draw&&(c[d].animate&&c[d].animate(a),c[d])){var f=-this.player.orient*Math.PI/180;if(Math.sin(f)*(c[d].x-this.player.x)+Math.cos(f)*(c[d].y-this.player.y)>0||e<-viewDist*2)c[d].modelName&&models[c[d].modelName].transparent?this.objectsWithAlpha.push(c[d]):c[d].draw()}}gl.enable(gl.BLEND);
for(c=0;c<this.objectsWithAlpha.length;c++)this.objectsWithAlpha[c].draw();this.objectsWithAlpha=[];gl.disable(gl.DEPTH_TEST);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);d=[];for(c=0;c<this.particles.length;c++)e=dist(this.player,this.particles[c].parent),e<b&&this.particles[c].draw(),this.particles[c].process(a),this.particles[c].alive&&this.particles[c].currentTime<this.particles[c].parts.duration?d.push(this.particles[c]):this.particles[c].finalize();this.particles=d;gl.enable(gl.DEPTH_TEST);gl.blendFunc(gl.SRC_ALPHA,
gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.BLEND)}};
